-- ============================================================
-- db-oracle/oracle-init.sql
-- Inicialización de Oracle para Railway con gvenzl/oracle-xe
-- Crea PDB, registra servicio, crea usuario BILLING,
-- tablas FACTURAS y FACTURA_ITEMS, y procedimiento REGISTER_INVOICE.
-- ============================================================

SET SERVEROUTPUT ON;

PROMPT === STEP 1: Crear PDB CASTOR si no existe ===

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM dba_pdbs
  WHERE pdb_name = 'CASTOR';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE CASTOR ADMIN USER castor_admin IDENTIFIED BY "CastorAdmin123"';
  END IF;
END;
/
PROMPT PDB CASTOR check done.


PROMPT === STEP 2: Abrir PDB CASTOR y guardar estado ===

BEGIN
  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE CASTOR OPEN';
  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE CASTOR SAVE STATE';
END;
/
PROMPT PDB CASTOR opened and state saved.


PROMPT === STEP 3: Registrar el servicio CASTOR en el Listener ===

ALTER SYSTEM SET service_names='CASTOR' SCOPE=BOTH;
ALTER SYSTEM REGISTER;

PROMPT Listener registration commands executed.


PROMPT === STEP 4: Crear usuario BILLING en CASTOR (si no existe) ===

ALTER SESSION SET CONTAINER = CASTOR;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM dba_users
  WHERE username = 'BILLING';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BILLING IDENTIFIED BY "Billing123" QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO BILLING';
  END IF;
END;
/
PROMPT User BILLING ready.


PROMPT === STEP 5: Crear tablas FACTURAS y FACTURA_ITEMS ===

-- FACTURAS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_tables
  WHERE table_name = 'FACTURAS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE FACTURAS (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        CLIENTE_ID NUMBER NOT NULL,
        SUBTOTAL NUMBER(10,2) NOT NULL,
        IMPUESTOS NUMBER(10,2) NOT NULL,
        DESCUENTOS NUMBER(10,2) NOT NULL,
        TOTAL NUMBER(10,2) NOT NULL,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )';
  END IF;
END;
/

-- FACTURA_ITEMS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_tables
  WHERE table_name = 'FACTURA_ITEMS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE FACTURA_ITEMS (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        FACTURA_ID NUMBER NOT NULL,
        PRODUCTO VARCHAR2(255) NOT NULL,
        PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
        CANTIDAD NUMBER NOT NULL,
        CONSTRAINT FK_FACTURA FOREIGN KEY (FACTURA_ID)
          REFERENCES FACTURAS(ID) ON DELETE CASCADE
      )';
  END IF;
END;
/
PROMPT Tables created or already exist.


PROMPT === STEP 6: Crear procedimiento REGISTER_INVOICE ===

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_objects
  WHERE object_type='PROCEDURE'
    AND object_name='REGISTER_INVOICE';

  IF v_count = 0 THEN

    EXECUTE IMMEDIATE '
      CREATE OR REPLACE PROCEDURE REGISTER_INVOICE(
        p_cliente_id IN NUMBER,
        p_subtotal   IN NUMBER,
        p_impuestos  IN NUMBER,
        p_descuentos IN NUMBER,
        p_total      IN NUMBER,
        p_cliente_existe IN VARCHAR2,
        p_factura_id OUT NUMBER,
        p_status     OUT VARCHAR2
      )
      AS
      BEGIN
        IF UPPER(TRIM(p_cliente_existe)) <> ''YES'' THEN
          p_status := ''ERROR: CLIENTE NO EXISTE'';
          p_factura_id := NULL;
          RETURN;
        END IF;

        INSERT INTO FACTURAS (CLIENTE_ID, SUBTOTAL, IMPUESTOS, DESCUENTOS, TOTAL)
        VALUES (p_cliente_id, p_subtotal, p_impuestos, p_descuentos, p_total)
        RETURNING ID INTO p_factura_id;

        p_status := ''OK'';
      EXCEPTION
        WHEN OTHERS THEN
          p_status := SQLERRM;
          p_factura_id := NULL;
      END;
    ';

  END IF;

END;
/
PROMPT Procedure REGISTER_INVOICE created or already exists.


PROMPT === Oracle Initialization Completed ===
